version: 2.1
jobs:
  build-server:
    docker:
      - image: cimg/go:1.17
        auth:
          username: techyfuzz123
          password: $DOCK_PASSWD  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          SERVER_TAG=1.1.$CIRCLE_BUILD_NUM
          docker build -t techyfuzz123/feedback-test:$SERVER_TAG ./server/
          echo $DOCK_PASSWD | docker login -u $DOCK_USER --password-stdin
          docker push techyfuzz123/feedback-test:$SERVER_TAG

  build-client:
    docker:
      - image: cimg/go:1.17
        auth:
          username: techyfuzz123
          password: $DOCK_PASSWD  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          CLIENT_TAG=1.1.$CIRCLE_BUILD_NUM
          docker build -t techyfuzz123/client-test:$SERVER_TAG ./client/
          echo $DOCK_PASSWD | docker login -u $DOCK_USER --password-stdin
          docker push techyfuzz123/client-test:$CLIENT_TAG
