name: Containerize Client

on:
  push:
    branches: [ "main" ]
      paths:
        - client/**

jobs:

  build-client:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCK_USERNAME }}
        password: ${{ secrets.DOCK_PASSWD }}
    - name: Setup buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and Push Client
      uses: docker/build-push-action@v3
      with:
        context: ./client
        tags: techyfuzz123/client-test:latest, techyfuzz123/client-test:${{ github.run_number }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
