name: Feedback-CI-CD

on:
  push:
    branches: [ "main" ]

jobs:

  checkout-diff:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
      client: ${{ steps.filter.outputs.client }}
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Check diff
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          server:
            - 'server/**'
          client:
            - 'client/**'
  

  build-server:
    needs: checkout-diff
    if: ${{ needs.checkout-diff.outputs.server == 'true' }}	
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCK_USERNAME }}
        password: ${{ secrets.DOCK_PASSWD }}
    - name: Setup buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and Push Server
      uses: docker/build-push-action@v3
      with:
        context: ./server
        tags: techyfuzz123/feedback-test:latest, techyfuzz123/feedback-test:${{ github.run_number }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-client:
    needs: checkout-diff
    if: ${{ needs.checkout-diff.outputs.client == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCK_USERNAME }}
        password: ${{ secrets.DOCK_PASSWD }}
    - name: Setup buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and Push Client
      uses: docker/build-push-action@v3
      with:
        context: ./client
        tags: techyfuzz123/client-test:latest, techyfuzz123/client-test:${{ github.run_number }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
